"""initial game schema"""
import sqlalchemy as sa
from alembic import op

revision = '2817241ad1ba'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motives',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_participants_per_chain', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_participants_per_chain >= 2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issuer', sa.String(length=500), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer', 'subject')
    )
    op.create_table('ai_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('deployment_name', sa.String(length=100), nullable=False),
    sa.Column('model_reference', sa.String(length=100), nullable=False),
    sa.Column('api_version', sa.String(length=40), nullable=False),
    sa.Column('auth_mode', sa.String(length=30), nullable=False),
    sa.Column('credential_reference', sa.String(length=100), nullable=False),
    sa.Column('generation_parameters', sa.JSON(), nullable=False),
    sa.Column('request_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision')
    )
    op.create_table('friendships',
    sa.Column('left_id', sa.String(length=36), nullable=False),
    sa.Column('right_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.CheckConstraint('left_id < right_id'),
    sa.ForeignKeyConstraint(['left_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('allow_random_participation', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_allow_random_participation'), 'user_settings', ['allow_random_participation'], unique=False)
    op.create_table('ai_assignments',
    sa.Column('task', sa.String(length=20), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['ai_profiles.id'], ),
    sa.PrimaryKeyConstraint('task')
    )
    op.create_table('chains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('setup', sa.Text(), nullable=False),
    sa.Column('rules', sa.String(length=500), nullable=False),
    sa.Column('group_mode', sa.String(length=20), nullable=False),
    sa.Column('source_group_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('publication_status', sa.String(length=20), nullable=False),
    sa.Column('publication_requester_id', sa.String(length=36), nullable=True),
    sa.Column('publication_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('turn_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('min_participants', sa.Integer(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.CheckConstraint('2 <= min_participants AND min_participants <= max_participants'),
    sa.CheckConstraint('turn_timeout_seconds > 0'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['publication_requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chains_published_at'), 'chains', ['published_at'], unique=False)
    op.create_index(op.f('ix_chains_status'), 'chains', ['status'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('work_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('task', sa.String(length=30), nullable=False),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['ai_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_work_items_available_at'), 'work_items', ['available_at'], unique=False)
    op.create_index(op.f('ix_work_items_status'), 'work_items', ['status'], unique=False)
    op.create_table('approvals',
    sa.Column('chain_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('chain_id', 'user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chain_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('participants',
    sa.Column('chain_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('contributed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('chain_id', 'user_id')
    )
    op.create_table('turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chain_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('motive_id', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('ai_assisted', sa.Boolean(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('fallback_index', sa.Integer(), nullable=True),
    sa.CheckConstraint('NOT (ai_assisted AND ai_generated)'),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.ForeignKeyConstraint(['motive_id'], ['motives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id', 'position'),
    sa.UniqueConstraint('chain_id', 'user_id')
    )
    op.create_index(op.f('ix_turns_chain_id'), 'turns', ['chain_id'], unique=False)
    op.create_index(op.f('ix_turns_deadline_at'), 'turns', ['deadline_at'], unique=False)
    op.create_index('one_active_turn', 'turns', ['chain_id'], unique=True, sqlite_where=sa.text("status != 'submitted'"), postgresql_where=sa.text("status != 'submitted'"))
    op.create_table('likes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chain_id', sa.String(length=36), nullable=True),
    sa.Column('turn_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('(chain_id IS NOT NULL AND turn_id IS NULL) OR (chain_id IS NULL AND turn_id IS NOT NULL)'),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chain_id'),
    sa.UniqueConstraint('user_id', 'turn_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_index('one_active_turn', table_name='turns', sqlite_where=sa.text("status != 'submitted'"), postgresql_where=sa.text("status != 'submitted'"))
    op.drop_index(op.f('ix_turns_deadline_at'), table_name='turns')
    op.drop_index(op.f('ix_turns_chain_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_table('participants')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_work_items_status'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_available_at'), table_name='work_items')
    op.drop_table('work_items')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_chains_status'), table_name='chains')
    op.drop_index(op.f('ix_chains_published_at'), table_name='chains')
    op.drop_table('chains')
    op.drop_table('ai_assignments')
    op.drop_index(op.f('ix_user_settings_allow_random_participation'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_table('login_sessions')
    op.drop_table('groups')
    op.drop_table('friendships')
    op.drop_table('ai_profiles')
    op.drop_table('users')
    op.drop_table('platform_settings')
    op.drop_table('motives')
    # ### end Alembic commands ###
